#site settings
title: Purvesh's Blog
author: Purvesh Makode
email: makodepurvesh@gmail.com
description: A space to express some thoughts and opinions
permalink: /:categories/:year/:month/:day/:title/ 
